run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert
    - unparam

linters-settings:
  govet:
    shadow: false
  gocritic:
    enabled-checks:
      - emptyFallthrough
      - equalFold
      - indexAlloc
      - nestingReduce
      - rangeValCopy
      - unnamedResult

issues:
  exclude-rules:
    # Test files can be more relaxed.
    - path: _test\.go
      linters:
        - errcheck
        - unparam
        - gocritic
    # Allow unused parameters in interface implementations.
    - linters:
        - unparam
      text: "always receives"
  max-issues-per-linter: 50
  max-same-issues: 10
